AneemBookBazaar.MVC.Web/Controllers/BookController.cs
using AneemBookBazaar.MVC.DataAccess;
using AneemBookBazaar.MVC.DataAccess.Repository.IRepository;
using AneemBookBazaar.MVC.Models.EntityModels;
using Microsoft.AspNetCore.Mvc;

namespace AneemBookBazaar.MVC.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IUnitOfWork _unitofWork;
        public BookController(IUnitOfWork unitofWork)
        {
            _unitofWork = unitofWork;

        }
        public IActionResult Index()
        {
            var bookList = _unitofWork.Book.GetAll();
            return View(bookList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Book book)
        {
            if (!ModelState.IsValid)
            {
                return View(book);
            }
            _unitofWork.Book.Add(book);
            _unitofWork.Save();
            TempData["Success"] = "Book created successfully";
            return RedirectToAction("Index");

        }
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Book book = _unitofWork.Book.Get(u => u.ID == id);
            if (book == null) { return NotFound(); }
            return View(book);

        }
        [HttpPost]
        public IActionResult Update(Book book)
        {
            if (!ModelState.IsValid)
            {
                return View(book);
            }
            //_context.Books.Update(book);
            //_context.SaveChanges();
            _unitofWork.Book.Update(book);
            _unitofWork.Save();
            TempData["Success"] = "Book updated successfully";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Book book = _unitofWork.Book.Get(x => x.ID == id);
            if (book == null) { return NotFound(); }
            return View(book);

        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var book = _unitofWork.Book.Get(x => x.ID == id);
            if (book == null) { return NotFound(); }
            _unitofWork.Book.Delete(book);
            _unitofWork.Save();
            TempData["Success"] = "Book deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

AneemBookBazaar.MVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AneemBookBazaar.MVC.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AneemBookBazaar.MVC.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aneem BookBazaar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                    </ul>
                 <partial name="_loginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AneemBookBazaar.MVC.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AneemBookBazaar.MVC.Web/Views/Shared/_NotificationMessage.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["Success"]');
    </script>
}
@if (TempData["Fail"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.Error('@TempData["Fail"]')
    </script>
}